"""Safety helpers for generated, disposable work directories."""

from __future__ import annotations

import shutil
from pathlib import Path

MARKER = ".pqc-rpki-generated"


def reset_generated_directory(path: Path, *, allowed_root: Path) -> Path:
    """Create or reset a marked directory strictly below ``allowed_root``."""
    target = path.resolve()
    root = allowed_root.resolve()
    if target == root or root not in target.parents:
        raise ValueError(f"generated directory must be below {root}: {target}")
    marker = target / MARKER
    if target.exists():
        if not marker.is_file():
            raise ValueError(f"refusing to delete unmarked directory: {target}")
        shutil.rmtree(target)
    target.mkdir(parents=True)
    (target / MARKER).write_text(
        "Generated by pqc-rpki-lab; this directory may be replaced.\n"
    )
    return target
